is_explainabilty: True

model:
  name: "LGBMClassifier"
  type: "classification"
  framework: "LightGBM"
  version: "1.0"

data_path: "C:/Users/user/Desktop/MiniProject Data Scientist/Classification Project/Data//raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"
